@extends('frontend.frontend-page-master')
@section('site-title')
    {{__('Works')}}
@endsection
@section('page-title')
    {{__('Works')}}
@endsection
@section('content')
    @include('frontend.partials.recent_projects')
@endsection
